Repository DevCycleHQ/js-sdks, pull requests merged in 2023-07, with the labels that each got.

#521 feat: DVC-8019 rename DVC to DevCycle NodeJS SDK + OF Provider
  examples/nodejs-cloud/js/README.md
  examples/nodejs-cloud/js/src/main.js
  examples/nodejs-cloud/typescript/README.md
  examples/nodejs-cloud/typescript/src/main.ts
  examples/nodejs-local/js/README.md
  examples/nodejs-local/js/src/main.js
  examples/nodejs-local/typescript/README.md
  examples/nodejs-local/typescript/src/benchmarkDVC.ts
  examples/nodejs-local/typescript/src/main.ts
  examples/openfeature-nodejs/README.md
  examples/openfeature-nodejs/src/main.ts
  lib/shared/bucketing-assembly-script/assembly/eventQueue/requestPayloadManager.ts
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
  sdk/nodejs/__tests__/client.spec.ts
  sdk/nodejs/__tests__/cloudClient.spec.ts
  sdk/nodejs/__tests__/initialize.spec.ts
  sdk/nodejs/__tests__/models/populatedUser.spec.ts
  sdk/nodejs/__tests__/models/user.spec.ts
  sdk/nodejs/src/bucketing.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/cloudClient.ts
  sdk/nodejs/src/environmentConfigManager.ts
  sdk/nodejs/src/eventQueue.ts
  sdk/nodejs/src/index.ts
  sdk/nodejs/src/models/populatedUser.ts
  sdk/nodejs/src/models/requestEvent.ts
  sdk/nodejs/src/models/user.ts
  sdk/nodejs/src/request.ts
  sdk/nodejs/src/types.ts
  sdk/openfeature-nodejs-provider/README.md
  sdk/openfeature-nodejs-provider/__tests__/DevCycleProvider.test.ts
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
Labels: 10 min review

#522 feat!: DVC-8013 rename @devcycle/devcycle-js-sdk repo to @devcycle/js-client-sdk
  examples/js/web-elements-app/src/app/app.element.ts
  scripts/npm-safe-publish.sh
  sdk/js/README.md
  sdk/js/package.json
  sdk/js/project.json
  sdk/react-native/src/ReactNativeCacheStore.ts
  sdk/react/__mocks__/@devcycle/js-client-sdk.ts
  sdk/react/src/DevCycleProvider.tsx
  sdk/react/src/context.ts
  sdk/react/src/index.ts
  sdk/react/src/initializeDevCycleClient.ts
  sdk/react/src/types.ts
  sdk/react/src/useDVCVariable.ts
  sdk/react/src/useDevCycleClient.ts
  sdk/react/src/useVariable.ts
  sdk/react/src/useVariableValue.test.tsx
  sdk/react/src/useVariableValue.ts
  tsconfig.base.json
  yarn.lock
Labels: 10 min review

#523 feat!: DVC-8014 rename react NPM repo to @devcycle/react-client-sdk
  examples/react/next-js-app/pages/_app.tsx
  examples/react/next-js-app/pages/index.tsx
  examples/react/with-provider/src/App.tsx
  examples/react/with-provider/src/DevCycleExample.tsx
  sdk/react-native/src/DevCycleProvider.tsx
  sdk/react-native/src/index.ts
  sdk/react-native/src/withDevCycleProvider.ts
  sdk/react/package.json
  sdk/react/project.json
  tsconfig.base.json
  yarn.lock
Labels: 5 min review

#524 feat!: DVC-8015 rename react native NPM repo to @devcycle/react-native-client-sdk
  sdk/react-native/package.json
  sdk/react-native/project.json
  tsconfig.base.json
  yarn.lock
Labels: 1 min review

#527 feat: DVC-8015 add disableAutomaticEventLogging and disableCustomEventLogging options
  sdk/js/__tests__/Client.spec.js
  sdk/js/__tests__/EventQueue.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/EventQueue.ts
  sdk/js/src/types.ts
Labels: 5 min review

#528 fix: issue with re-rendering component React SDK
  package.json
  sdk/react/__mocks__/@devcycle/js-client-sdk.ts
  sdk/react/mockData/mockConfig.ts
  sdk/react/package.json
  sdk/react/src/useVariable.ts
  sdk/react/src/useVariableValue.integration.test.tsx
  sdk/react/src/useVariableValue.test.tsx
  yarn.lock
Labels: 5 min review

#531 fix: update npm publish script to also call npm deprecate
  scripts/npm-safe-publish.sh
Labels: 1 min review

#534 chore: add README for React Native example app
  examples/react/react-native-app/README.md
Labels: 1 min review, safe-changes

#535 fix: properly lock nodejs event flushing
  sdk/nodejs/__tests__/eventQueue.test.ts
  sdk/nodejs/src/eventQueue.ts
Labels: 5 min review

#536 fix: running debug WASM when debug logging is set, fix 'Failed to download config' debug log from 304 response
  examples/nodejs-local/typescript/src/benchmarkDVC.ts
  sdk/nodejs/__tests__/environmentConfigManager.spec.ts
  sdk/nodejs/src/bucketing.ts
  sdk/nodejs/src/environmentConfigManager.ts
  sdk/nodejs/src/request.ts
  yarn.lock
Labels: 1 min review
