Repository DevCycleHQ/js-sdks, pull requests merged in 2023-10, with the labels that each got.

#540 feat: add react-native-expo package
  lib/shared/types/project.json
  lib/shared/types/tsconfig.lib.es5.json
  package.json
  sdk/js/project.json
  sdk/js/tsconfig.lib.es5.json
  sdk/react-native-expo/.eslintrc.json
  sdk/react-native-expo/README.md
  sdk/react-native-expo/babel.config.json
  sdk/react-native-expo/jest.config.ts
  sdk/react-native-expo/package.json
  sdk/react-native-expo/project.json
  sdk/react-native-expo/src/DevCycleProvider.tsx
  sdk/react-native-expo/src/ReactNativeCacheStore.ts
  sdk/react-native-expo/src/index.ts
  sdk/react-native-expo/src/withDevCycleProvider.ts
  sdk/react-native-expo/test-setup.ts
  sdk/react-native-expo/tsconfig.json
  sdk/react-native-expo/tsconfig.lib.json
  sdk/react-native-expo/tsconfig.spec.json
  sdk/react/project.json
  sdk/react/tsconfig.lib.es5.json
  tsconfig.base.json
  yarn.lock
Labels: 10 min review

#568 fix: React Native Expo build fix
  package.json
  sdk/react-native-expo/project.json
  yarn.lock
Labels: 1 min review

#560 feat: DVC-9055 extract JS Cloud Bucketing SDK from NodeJS SDK
  package.json
  sdk/js-cloud-server/.babelrc
  sdk/js-cloud-server/.eslintrc.json
  sdk/js-cloud-server/.gitignore
  sdk/js-cloud-server/README.md
  sdk/js-cloud-server/__mocks__/cross-fetch.ts
  sdk/js-cloud-server/__mocks__/fetch-retry.ts
  sdk/js-cloud-server/__tests__/cloudClient.spec.ts
  sdk/js-cloud-server/__tests__/initialize.spec.ts
  sdk/js-cloud-server/__tests__/models/populatedUser.spec.ts
  sdk/js-cloud-server/__tests__/models/user.spec.ts
  sdk/js-cloud-server/__tests__/models/variable.spec.ts
  sdk/js-cloud-server/__tests__/request.spec.ts
  sdk/js-cloud-server/__tests__/utils/logger.spec.ts
  sdk/js-cloud-server/__tests__/utils/paramUtils.spec.ts
  sdk/js-cloud-server/jest.config.ts
  sdk/js-cloud-server/package.json
  sdk/js-cloud-server/project.json
  sdk/js-cloud-server/src/__mocks__/handlers.ts
  sdk/js-cloud-server/src/__mocks__/server.ts
  sdk/js-cloud-server/src/cloudClient.ts
  sdk/js-cloud-server/src/index.ts
  sdk/js-cloud-server/src/models/populatedUser.ts
  sdk/js-cloud-server/src/models/user.ts
  sdk/js-cloud-server/src/models/variable.ts
  sdk/js-cloud-server/src/request.ts
  sdk/js-cloud-server/src/types.ts
  sdk/js-cloud-server/src/utils/logger.ts
  sdk/js-cloud-server/src/utils/paramUtils.ts
  sdk/js-cloud-server/tsconfig.json
  sdk/js-cloud-server/tsconfig.lib.json
  sdk/js-cloud-server/tsconfig.spec.json
  sdk/nodejs/__tests__/client.spec.ts
  sdk/nodejs/__tests__/environmentConfigManager.spec.ts
  sdk/nodejs/__tests__/eventQueue.test.ts
  sdk/nodejs/__tests__/models/populatedPBUser.spec.ts
  sdk/nodejs/__tests__/models/user.spec.ts
  sdk/nodejs/__tests__/request.spec.ts
  sdk/nodejs/src/bucketing.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/cloudClient.ts
  sdk/nodejs/src/environmentConfigManager.ts
  sdk/nodejs/src/eventQueue.ts
  sdk/nodejs/src/index.ts
  sdk/nodejs/src/models/populatedUser.ts
  sdk/nodejs/src/models/populatedUserHelpers.ts
  sdk/nodejs/src/models/requestEvent.ts
  sdk/nodejs/src/request.ts
  sdk/nodejs/src/utils/platformDetails.ts
  sdk/nodejs/src/utils/userBucketingHelper.ts
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
  tsconfig.base.json
  yarn.lock
Labels: 20 min review

#569 feat: add option for bootstrapping config in JS SDK
  sdk/js/__tests__/Client.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/types.ts
  sdk/react/src/initializeDevCycleClient.ts
Labels: 5 min review

#561 feat: DVC-9055 adding Cloudflare Worker example app for new js-cloud-server-sdk
  .github/workflows/cf-worker-example-test.yml
  examples/js-cloud-server/cloudflare-worker/.eslintrc.json
  examples/js-cloud-server/cloudflare-worker/.gitignore
  examples/js-cloud-server/cloudflare-worker/README.md
  examples/js-cloud-server/cloudflare-worker/package.json
  examples/js-cloud-server/cloudflare-worker/project.json
  examples/js-cloud-server/cloudflare-worker/src/index.ts
  examples/js-cloud-server/cloudflare-worker/tsconfig.app.json
  examples/js-cloud-server/cloudflare-worker/tsconfig.json
  examples/js-cloud-server/cloudflare-worker/wrangler.toml
  package.json
  yarn.lock
Labels: 5 min review

#571 chore: dependabot
  .github/dependabot.yml
  .prettierignore
Labels: 1 min review

#575 chore(deps): update protobuf, fix compile-pb-as command
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataType.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataValue.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/DVCUser_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableCustomData.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableDouble.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableString.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/SDKVariable_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableForUserParams_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableType_PB.ts
  lib/shared/bucketing-assembly-script/package.json
  lib/shared/bucketing-assembly-script/project.json
  package.json
  yarn.lock
Labels: 5 min review

#577 chore(deps): update react-devtools-core dep to resolve dependabot alert
  package.json
  yarn.lock
Labels: 1 min review

#578 chore(deps): update ua-parser-js from dependabot alert
  package.json
  yarn.lock
Labels: 1 min review

#570 chore: app router example for next
  .gitignore
  examples/nextjs/app-router/.eslintrc.json
  examples/nextjs/app-router/app/layout.tsx
  examples/nextjs/app-router/app/page.tsx
  examples/nextjs/app-router/app/providers.tsx
  examples/nextjs/app-router/index.d.ts
  examples/nextjs/app-router/next-env.d.ts
  examples/nextjs/app-router/next.config.js
  examples/nextjs/app-router/package.json
  examples/nextjs/app-router/pages/_error.tsx
  examples/nextjs/app-router/pages/api/hello.ts
  examples/nextjs/app-router/project.json
  examples/nextjs/app-router/public/favicon.ico
  examples/nextjs/app-router/public/vercel.svg
  examples/nextjs/app-router/styles/Home.module.css
  examples/nextjs/app-router/styles/globals.css
  examples/nextjs/app-router/tsconfig.json
  examples/nextjs/app-router/tsconfig.spec.json
  examples/nextjs/pages-router/.eslintrc.json
  examples/nextjs/pages-router/index.d.ts
  examples/nextjs/pages-router/next-env.d.ts
  examples/nextjs/pages-router/next.config.js
  examples/nextjs/pages-router/package.json
  examples/nextjs/pages-router/pages/_app.tsx
  examples/nextjs/pages-router/pages/_error.tsx
  examples/nextjs/pages-router/pages/api/hello.ts
  examples/nextjs/pages-router/pages/index.tsx
  examples/nextjs/pages-router/project.json
  examples/nextjs/pages-router/public/favicon.ico
  examples/nextjs/pages-router/public/vercel.svg
  examples/nextjs/pages-router/styles/Home.module.css
  examples/nextjs/pages-router/styles/globals.css
  examples/nextjs/pages-router/tsconfig.json
  examples/nextjs/pages-router/tsconfig.spec.json
  package.json
  sdk/react/src/withDevCycleProvider.tsx
  yarn.lock
Labels: 10 min review

#580 chore(deps): update @adobe/css-tools from dependabot alert
  package.json
  yarn.lock
Labels: 1 min review

#582 chore(deps): update word-wrap dep with resolution
  package.json
  yarn.lock
Labels: 1 min review

#583 chore(deps): update @sideway/formula with resolution to resolve dep alert
  package.json
  yarn.lock
Labels: 1 min review

#564 feat: DVC-9059 pull out EnvironmentConfigManager to its own library, change nodejs build to define external pacakges
  lib/shared/config-manager/.eslintrc.json
  lib/shared/config-manager/README.md
  lib/shared/config-manager/__mocks__/cross-fetch.ts
  lib/shared/config-manager/__mocks__/fetch-retry.ts
  lib/shared/config-manager/__tests__/environmentConfigManager.spec.ts
  lib/shared/config-manager/__tests__/request.spec.ts
  lib/shared/config-manager/jest.config.ts
  lib/shared/config-manager/package.json
  lib/shared/config-manager/project.json
  lib/shared/config-manager/src/index.ts
  lib/shared/config-manager/src/request.ts
  lib/shared/config-manager/tsconfig.json
  lib/shared/config-manager/tsconfig.lib.json
  lib/shared/config-manager/tsconfig.spec.json
  sdk/nodejs/__tests__/client.spec.ts
  sdk/nodejs/__tests__/initialize.spec.ts
  sdk/nodejs/package.json
  sdk/nodejs/project.json
  sdk/nodejs/src/bucketing.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/request.ts
  sdk/nodejs/tsconfig.lib.json
  tsconfig.base.json
  yarn.lock
Labels: 10 min review

#565 feat: DVC9059 move core server request logic to new lib
  lib/shared/config-manager/__tests__/environmentConfigManager.spec.ts
  lib/shared/config-manager/src/index.ts
  lib/shared/config-manager/src/request.ts
  lib/shared/server-request/.eslintrc.json
  lib/shared/server-request/README.md
  lib/shared/server-request/__mocks__/cross-fetch.ts
  lib/shared/server-request/__mocks__/fetch-retry.ts
  lib/shared/server-request/__tests__/request.spec.ts
  lib/shared/server-request/jest.config.ts
  lib/shared/server-request/package.json
  lib/shared/server-request/project.json
  lib/shared/server-request/src/index.ts
  lib/shared/server-request/src/request.ts
  lib/shared/server-request/src/userError.ts
  lib/shared/server-request/tsconfig.json
  lib/shared/server-request/tsconfig.lib.json
  lib/shared/server-request/tsconfig.spec.json
  sdk/js-cloud-server/src/cloudClient.ts
  sdk/js-cloud-server/src/request.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/request.ts
  tsconfig.base.json
  yarn.lock
Labels: 10 min review

#585 chore(deps): update nx to 16.5.5
  migrations.json
  package.json
  yarn.lock
Labels: 1 min review

#576 chore(deps): update mock service worker
  lib/shared/server-request/src/request.ts
  package.json
  sdk/js-cloud-server/__tests__/cloudClient.spec.ts
  sdk/js-cloud-server/__tests__/initialize.spec.ts
  sdk/js-cloud-server/src/__mocks__/handlers.ts
  yarn.lock
Labels: 5 min review

#592 fix: example app types
  package.json
  yarn.lock
Labels: 1 min review

#590 fix: Use populated user when checking if user is anonymous
  sdk/js/__tests__/Client.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/types.ts
Labels: 1 min review

#591 fix: Update nx patch to apply to 16.5.5
  package.json
  yarn.lock
Labels: 1 min review
