Repository DevCycleHQ/js-sdks, pull requests merged in 2023-02, with the labels that each got.

#387 feat: add audienceMatch type
  lib/shared/types/src/types/config/models/audience.ts
Labels: 1 min review

#389 DVC-6012 update UserEventsBatchRecord to filter out privateCustomData
  lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcEvent.ts
  yarn.lock
Labels: 5 min review

#388 add audiences fields
  lib/shared/bucketing-assembly-script/assembly/helpers/jsonHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/types/src/types/config/configBody.ts
  lib/shared/types/src/types/config/models/audience.ts
Labels: 5 min review

#391 make audience optional
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/types/src/types/config/configBody.ts
Labels: 5 min review

#395 Pass IdType down to AudienceFilterOrOperator from Audience
  lib/shared/types/src/types/config/models/audience.ts
Labels: 5 min review

#379 DVC-5923 rename envKey to sdkKey in NodeJS SDK
  examples/nodejs-cloud/js/src/main.js
  examples/nodejs-cloud/typescript/src/main.ts
  examples/nodejs-local/js/src/main.js
  examples/nodejs-local/typescript/src/main.ts
  sdk/nodejs/__tests__/environmentConfigManager.spec.ts
  sdk/nodejs/__tests__/eventQueue.test.ts
  sdk/nodejs/__tests__/request.spec.ts
  sdk/nodejs/src/environmentConfigManager.ts
  sdk/nodejs/src/eventQueue.ts
  sdk/nodejs/src/index.ts
  sdk/nodejs/src/request.ts
  sdk/nodejs/src/utils/paramUtils.ts
  yarn.lock
Labels: 5 min review

#380 DVC-5923 rename envKey / token to sdkKey in Bucketing AS library
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
  lib/shared/bucketing-assembly-script/assembly/eventQueue/eventQueue.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/managers/configDataManager.ts
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
Labels: 5 min review

#396 pass IdType down to Audience from ConfigBody
  lib/shared/types/src/types/config/configBody.ts
Labels: 1 min review

#397 chore: pass idtype to recursive filter definition
  lib/shared/types/src/types/config/models/audience.ts
Labels: 1 min review

#398 chore: omit _id from configBody audiences
  lib/shared/types/src/types/config/configBody.ts
Labels: 1 min review

#399 fix: allow unknown comparators for forwards compatibility
  lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
Labels: 5 min review

#400 add bucketing logic and tests for bucketing.ts supporting reusable auds
  lib/shared/bucketing/__test__/bucketing.test.ts
  lib/shared/bucketing/__test__/segmentation.test.ts
  lib/shared/bucketing/src/bucketing.ts
  lib/shared/bucketing/src/segmentation.ts
Labels: 5 min review

#386 fix: calling flushEvents multiple times should result in one flush
  sdk/nodejs/src/eventQueue.ts
Labels: 5 min review

#401 feat: add client custom data to bucketing
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/managers/clientCustomDataManager.ts
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
Labels: 5 min review

#402 fix: evaluate false for audienceMatch rules referencing a non-existent audience
  lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing/__test__/segmentation.test.ts
  lib/shared/bucketing/src/segmentation.ts
Labels: 5 min review

#404 feat: added support for nested filters in bucketing
  lib/shared/bucketing/__test__/bucketing.test.ts
  lib/shared/bucketing/src/segmentation.ts
Labels: 5 min review

#403 Add nested filter support in bucketing wasm
  lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
  lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/bucketing/__test__/bucketing.test.ts
  lib/shared/bucketing/src/segmentation.ts
Labels: 5 min review

#405 feat: add client custom data to user custom data when tracking events
  lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
  lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
Labels: 5 min review

#406 fix: react useVariable hook will only call the variable method once
  sdk/react/__mocks__/@devcycle/devcycle-js-sdk.ts
  sdk/react/src/useVariable.ts
  sdk/react/src/useVariableValue.test.tsx
Labels: 5 min review

#408 DVC-5923 Rename environmentKey to sdkKey to be consistent across SDKs
  examples/react/react-native-app/README.md
  examples/react/with-async-provider/README.md
  examples/react/with-provider/README.md
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
  sdk/js/__tests__/Request.spec.ts
  sdk/js/__tests__/index.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/EventQueue.ts
  sdk/js/src/Request.ts
  sdk/js/src/index.ts
  sdk/js/src/types.ts
  sdk/nodejs/__tests__/initialize.spec.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/cloudClient.ts
  sdk/nodejs/src/index.ts
  sdk/react/src/initializeDVCClient.ts
  yarn.lock
Labels: 5 min review

#409 DVC-6240 prefix env keys with NX
  examples/js/web-elements-app/src/app/app.element.ts
  examples/react/next-js-app/pages/_app.tsx
  examples/react/react-native-app/src/app/App.tsx
  examples/react/with-async-provider/src/index.tsx
  examples/react/with-provider/src/App.tsx
Labels: 5 min review

#407 DVC-0000: add umd instructions
  README.md
Labels: 1 min review, safe-changes
