Repository DevCycleHQ/js-sdks, pull requests merged in 2023-08, with the labels that each got.

#537 feat: add flushEventQueueSize and maxEventQueueSize options to control JS SDK event queue behaviour
  sdk/js/__tests__/EventQueue.spec.js
  sdk/js/src/EventQueue.ts
  sdk/js/src/types.ts
  sdk/nodejs/__tests__/eventQueue.test.ts
  sdk/nodejs/src/eventQueue.ts
Labels: 20 min review

#538 fix: add 10 sec sleep to make npm publish script work with npm deprecate
  scripts/npm-safe-publish.sh
Labels: 1 min review

#541 chore: add debugusers field to config type
  lib/shared/types/src/types/config/configBody.ts
Labels: 1 min review

#542 chore: add targeting type field
  lib/shared/types/src/types/config/models/featureConfiguration.ts
Labels: 1 min review

#545 feat: Use new published package for asc-json
  lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing-assembly-script/assembly/eventQueue/requestPayloadManager.ts
  lib/shared/bucketing-assembly-script/assembly/helpers/jsonHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/managers/clientCustomDataManager.ts
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcEvent.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
  lib/shared/bucketing-assembly-script/assembly/types/eventQueueOptions.ts
  lib/shared/bucketing-assembly-script/assembly/types/feature.ts
  lib/shared/bucketing-assembly-script/assembly/types/featureConfiguration.ts
  lib/shared/bucketing-assembly-script/assembly/types/platformData.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
  package.json
  yarn.lock
Labels: 5 min review

#544 feat: add overrides support to bucketing and add tests
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing/__test__/bucketing.test.ts
  lib/shared/bucketing/src/bucketing.ts
Labels: 5 min review

#546 fix: protobuf building files, only compile them with 'nx run shared-bucketing-as:compile-pb' command
  lib/shared/bucketing-assembly-script/README.md
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataType.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataValue.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/DVCUser_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableCustomData.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableDouble.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableString.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/SDKVariable_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableForUserParams_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableType_PB.ts
  lib/shared/bucketing-assembly-script/project.json
Labels: 5 min review

#548 chore: yarn in pnpm mode
  .github/workflows/nx-affected-test.yml
  .github/workflows/run-test-harness.yml
  .yarnrc.yml
  examples/nodejs-cloud/js/src/main.js
  examples/nodejs-cloud/typescript/src/main.ts
  examples/nodejs-local/js/src/main.js
  examples/nodejs-local/typescript/src/main.ts
  lib/shared/bucketing-assembly-script/index.js
  package.json
  yarn.lock
Labels: 1 min review

#549 fix: add protobufjs dependency to assemblyscript lib
  lib/shared/bucketing-assembly-script/package.json
  yarn.lock
Labels: 1 min review

#551 fix: cleanup EventListener for Page Hide event
  sdk/js/src/Client.ts
  sdk/js/src/index.ts
Labels: 1 min review

#552 fix: DVC initialized hook rerender
  sdk/js/src/Client.ts
  sdk/react/__mocks__/@devcycle/js-client-sdk.ts
  sdk/react/src/DevCycleProvider.tsx
  sdk/react/src/context.ts
  sdk/react/src/useIsDevCycleInitialized.test.tsx
  sdk/react/src/useIsDevCycleInitialized.ts
Labels: 5 min review
