Repository DevCycleHQ/js-sdks, pull requests merged in 2023-01, with the labels that each got.

#372 Comment workflow url when running test harness
  .github/workflows/run-test-harness.yml
Labels: 1 min review, safe-changes

#370 Always throw when the request error is a 4xx error
  examples/nodejs-cloud/js/project.json
  examples/nodejs-cloud/typescript/project.json
  examples/nodejs-local/js/project.json
  examples/nodejs-local/typescript/project.json
  sdk/nodejs/__tests__/cloudClient.spec.ts
  sdk/nodejs/src/__mocks__/handlers.ts
  sdk/nodejs/src/cloudClient.ts
  sdk/nodejs/src/request.ts
  yarn.lock
Labels: 10 min review

#373 yarn lock for release
  yarn.lock
Labels: 1 min review

#374 Add PR title to github workflow payload
  .github/workflows/run-test-harness.yml
Labels: 1 min review, safe-changes

#278 use fetch API and node-fetch (fallback) for NodeJS SDK
  package.json
  sdk/nodejs/__mocks__/cross-fetch.ts
  sdk/nodejs/__mocks__/fetch-retry.ts
  sdk/nodejs/__tests__/client.spec.ts
  sdk/nodejs/__tests__/cloudClient.spec.ts
  sdk/nodejs/__tests__/environmentConfigManager.spec.ts
  sdk/nodejs/__tests__/eventQueue.test.ts
  sdk/nodejs/__tests__/request.spec.ts
  sdk/nodejs/src/cloudClient.ts
  sdk/nodejs/src/environmentConfigManager.ts
  sdk/nodejs/src/eventQueue.ts
  sdk/nodejs/src/request.ts
  sdk/nodejs/tsconfig.spec.json
  tsconfig.base.json
  yarn.lock
Labels: 30 min review

#375 updated Examples react and js web elemennts
  examples/js/web-elements-app/src/app/app.element.ts
  examples/react/next-js-app/pages/index.tsx
  examples/react/with-async-provider/src/DevCycleExample.tsx
  examples/react/with-provider/src/DevCycleExample.tsx
  yarn.lock
Labels: 10 min review

#376 examples react and web js elements updates
  examples/js/web-elements-app/src/app/app.element.ts
  examples/react/next-js-app/pages/index.tsx
  examples/react/with-async-provider/src/DevCycleExample.tsx
  examples/react/with-provider/src/DevCycleExample.tsx
Labels: 5 min review

#377 small react with provider example update
  examples/react/with-provider/src/DevCycleExample.tsx
Labels: 1 min review

#378 small update to react with provider example
  examples/react/with-provider/src/DevCycleExample.tsx
Labels: 1 min review

#383 fix: stop config polling when a 403 is received
  sdk/nodejs/__tests__/environmentConfigManager.spec.ts
  sdk/nodejs/src/environmentConfigManager.ts
Labels: 1 min review

#382 wait for flush
  sdk/nodejs/src/client.ts
Labels: 1 min review

#384 fix: error code handling on config manager
  sdk/nodejs/__tests__/environmentConfigManager.spec.ts
  sdk/nodejs/src/environmentConfigManager.ts
  sdk/nodejs/src/request.ts
Labels: 1 min review

#385 feat: added class for user error to prevent swallowing of errors to throw
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/environmentConfigManager.ts
  sdk/nodejs/src/utils/userError.ts
  yarn.lock
Labels: 5 min review
