Repository DevCycleHQ/js-sdks, pull requests merged in 2023-03, with the labels that each got.

#411 Update test harness trigger
  .github/workflows/run-test-harness.yml
Labels: safe-changes, 5 min review

#410 fix: log variable defaulted event when variable called before initialization
  sdk/nodejs/src/client.ts
Labels: 5 min review

#412 chore: remove date field and only send client date for request events
  sdk/nodejs/__tests__/models/requestEvent.spec.ts
  sdk/nodejs/src/models/requestEvent.ts
Labels: 1 min review

#415 DVC-6379 update AssemblyScript to 0.27.1
  lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
  lib/shared/bucketing-assembly-script/__tests__/bucketingImportHelper.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
  lib/shared/bucketing-assembly-script/index.d.ts
  lib/shared/bucketing-assembly-script/index.js
  package.json
  sdk/nodejs/package.json
  yarn.lock
Labels: 5 min review

#416 chore: include hostname in dvcpopulateduser
  lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
  sdk/nodejs/src/models/populatedUser.ts
Labels: 5 min review

#413 DVC-6473 add variableForUser() method to WASM code
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
  lib/shared/bucketing-assembly-script/__tests__/setPlatformData.ts
  lib/shared/bucketing-assembly-script/__tests__/variable.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
  lib/shared/bucketing-assembly-script/assembly/eventQueue/eventQueue.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
  lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcEvent.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
  lib/shared/bucketing-assembly-script/assembly/types/feature.ts
  lib/shared/bucketing-assembly-script/assembly/types/featureConfiguration.ts
  lib/shared/bucketing-assembly-script/assembly/types/platformData.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
  lib/shared/bucketing-assembly-script/index.js
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/bucketing/__test__/bucketing.test.ts
  sdk/nodejs/__tests__/eventQueue.test.ts
Labels: 20 min review

#417 fix: added null check for hostname in stringify
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
Labels: 1 min review

#421 chore: clean up double call to generateboundedhash
  lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
Labels: 5 min review

#418 DVC-6504 update variableType param in variableForUser() to be an enum
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/__tests__/variable.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/bucketing/__test__/bucketing.test.ts
  lib/shared/types/src/types/config/models/variable.ts
  lib/shared/types/src/utils.ts
Labels: 5 min review

#419 DVC-6484 add hasConfigData() WASM method
  lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/managers/configDataManager.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  sdk/nodejs/src/environmentConfigManager.ts
Labels: 5 min review

#420 DVC-6502 remove variableHashes from bucketed config output
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
  lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/bucketing/__test__/bucketing.test.ts
  lib/shared/bucketing/src/bucketing.ts
  lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
  lib/shared/types/src/types/config/configBody.ts
  sdk/nodejs/__tests__/eventQueue.test.ts
Labels: 5 min review

#425 DVC-6517 update UserFilter class to pre-compile string / bool / num values
  lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
Labels: 5 min review

#427 DVC-6519 protobuf interface for variableForUser
  .gitattributes
  .github/workflows/nx-affected-test.yml
  .github/workflows/run-test-harness.yml
  lib/shared/bucketing-assembly-script/.eslintrc.json
  lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
  lib/shared/bucketing-assembly-script/__tests__/types/protobuf.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
  lib/shared/bucketing-assembly-script/assembly/types/index.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataType.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataValue.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/DVCUser_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableCustomData.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableDouble.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableString.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/SDKVariable_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableForUserParams_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableType_PB.ts
  lib/shared/bucketing-assembly-script/package.json
  lib/shared/bucketing-assembly-script/project.json
  lib/shared/bucketing-assembly-script/protobuf/variableForUserParams.proto
  lib/shared/bucketing-test-data/project.json
  package.json
  scripts/brew-install.sh
  sdk/js/src/DefaultCacheStore.ts
  sdk/nodejs/project.json
  yarn.lock
Labels: 10 min review

#431 DVC-6574 add variableForUser_PB_Preallocated method
  lib/shared/bucketing-assembly-script/__tests__/types/protobuf.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
Labels: 5 min review

#432 Fix number typing in Protobuf
  lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
  yarn.lock
Labels: 1 min review

#434 DVC-6570 run all bucketing tests against variableForUser() and variableForUserPB()
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/__tests__/protobufVariableHelper.ts
  lib/shared/bucketing-assembly-script/__tests__/types/protobuf.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
Labels: 5 min review

#433 DVC-6132 [fix]: downgrade some JS SDK error logs to warning logs
  sdk/js/src/Client.ts
  sdk/js/src/Request.ts
  sdk/js/src/StreamingConnection.ts
Labels: 5 min review

#439 fix: use dummy string field to stop unmanaged class decorator
  lib/shared/bucketing-assembly-script/__tests__/types/protobuf.test.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableDouble.ts
  lib/shared/bucketing-assembly-script/protobuf/variableForUserParams.proto
Labels: 5 min review

#440 DVC-6132 [fix]: update realtime connection onerror logs to be warning
  sdk/js/src/Request.ts
  sdk/js/src/StreamingConnection.ts
Labels: 5 min review

#442 Add configUpdated event
  sdk/js/__tests__/EventEmitter.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/EventEmitter.ts
Labels: 10 min review

#438 Call variableUpdated subscriber with null if variable not in config
  sdk/js/__tests__/EventEmitter.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/EventEmitter.ts
Labels: 5 min review

#444 Added proto file header for Go generation
  lib/shared/bucketing-assembly-script/protobuf/variableForUserParams.proto
Labels: 1 min review

#435 DVC-6487 switch NodeJS SDK to use variableForUser()
  sdk/nodejs/__tests__/client.spec.ts
  sdk/nodejs/src/__mocks__/bucketing.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/utils/userBucketingHelper.ts
Labels: 5 min review

#436 DVC-6487 switch NodeJS SDK to use protobuf interface for variableForUser()
  .gitattributes
  lib/shared/bucketing-assembly-script/.eslintrc.json
  lib/shared/bucketing-assembly-script/__tests__/protobufVariableHelper.ts
  lib/shared/bucketing-assembly-script/index.d.ts
  lib/shared/bucketing-assembly-script/index.js
  lib/shared/bucketing-assembly-script/project.json
  lib/shared/bucketing-assembly-script/protobuf/compiled.d.ts
  lib/shared/bucketing-assembly-script/protobuf/compiled.js
  package.json
  sdk/nodejs/.eslintrc.json
  sdk/nodejs/__tests__/client.spec.ts
  sdk/nodejs/__tests__/models/user.spec.ts
  sdk/nodejs/project.json
  sdk/nodejs/src/__mocks__/bucketing.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/models/populatedUser.ts
  sdk/nodejs/src/pb-types/pbTypeHelpers.ts
  sdk/nodejs/src/utils/userBucketingHelper.ts
  yarn.lock
Labels: 30 min review

#446 Dispatch real events in eventEmitter
  sdk/js/__tests__/EventEmitter.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/EventEmitter.ts
Labels: 5 min review

#453 DVC-0000: stress that files uploaded to s3 need to be public
  README.md
Labels: 1 min review, safe-changes

#448 DVC-6558 Bucketing Assembly Script lib benchmarks
  lib/shared/bucketing-assembly-script/.gitignore
  lib/shared/bucketing-assembly-script/README.md
  lib/shared/bucketing-assembly-script/__benchmarks__/variable.bench.ts
  lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
  lib/shared/bucketing-assembly-script/__tests__/bucketingImportHelper.ts
  lib/shared/bucketing-assembly-script/__tests__/variable.test.ts
  lib/shared/bucketing-assembly-script/__tests__/variableSetupHelper.ts
  lib/shared/bucketing-assembly-script/jest-bench.config.ts
  lib/shared/bucketing-assembly-script/project.json
  lib/shared/bucketing-test-data/src/data/largeConfig.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/bucketing-test-data/src/index.ts
  lib/shared/bucketing/__test__/bucketing.test.ts
  package.json
  yarn.lock
Labels: 10 min review

#454 chore: reduce initial wasm memory
  lib/shared/bucketing-assembly-script/project.json
Labels: 1 min review

#456 Add basic config validation when reading from cache
  sdk/js/__tests__/Client.spec.js
  sdk/js/src/CacheStore.ts
Labels: 5 min review

#452 Add setConfigDataUTF8() method to Bucketing AS
  lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  sdk/nodejs/__tests__/environmentConfigManager.spec.ts
  sdk/nodejs/src/__mocks__/bucketing.ts
  sdk/nodejs/src/environmentConfigManager.ts
Labels: 5 min review

#455 Document each bucketing as lib index.ts method
  lib/shared/bucketing-assembly-script/assembly/index.ts
Labels: 5 min review

#458 DVC-6731 - Adding UTF8 functions for platform data and client custom data
  lib/shared/bucketing-assembly-script/__tests__/types/platformData.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/platformData.ts
Labels: 5 min review

#450 Benchmarking in NodeJS example app
  examples/nodejs-local/typescript/project.json
  examples/nodejs-local/typescript/src/benchmarkDVC.ts
  examples/nodejs-local/typescript/src/main.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/managers/clientCustomDataManager.ts
  lib/shared/bucketing-assembly-script/index.d.ts
  lib/shared/bucketing-assembly-script/index.js
  sdk/nodejs/src/bucketing.ts
Labels: 5 min review

#459 Update publishing instructions in readme
  README.md
Labels: 1 min review, safe-changes

#460 Adding UTF8 version of getBucketedConfigForUser
  lib/shared/bucketing-assembly-script/__tests__/types/dvcUser.test.ts
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
Labels: 5 min review

#461 Updated as-protobuf 1.3.0
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataType.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/CustomDataValue.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/DVCUser_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableCustomData.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableDouble.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableString.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/SDKVariable_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableForUserParams_PB.ts
  lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/VariableType_PB.ts
  package.json
  yarn.lock
Labels: 5 min review

#462 change garbage collection params
  lib/shared/bucketing-assembly-script/project.json
Labels: 1 min review

#465 chore(typescript): emit 3.5 types
  lib/shared/types/package.json
  lib/shared/types/project.json
  sdk/js/package.json
  sdk/js/project.json
Labels: 5 min review

#466 fix: dependsOn hierarchy for legacy types
  lib/shared/types/project.json
  sdk/js/project.json
Labels: 5 min review
