Repository DevCycleHQ/js-sdks, pull requests merged in 2023-09, with the labels that each got.

#554 fix: example apps __dirname refrences
  examples/nodejs-local/js/project.json
  examples/nodejs-local/js/webpack.config.js
  examples/nodejs-local/typescript/project.json
  examples/nodejs-local/typescript/webpack.config.js
  examples/openfeature-nodejs/project.json
  examples/openfeature-nodejs/webpack.config.js
Labels: 1 min review

#555 fix: Use dynamic import of bucketing-lib for debug/release
  lib/shared/bucketing-assembly-script/index.js
Labels: 1 min review

#556 ci: Add a skeleton release workflow to allow testing on GA
  .github/workflows/release.yml
Labels: 5 min review

#557 fix: Defer React SDK initialization on server
  sdk/react/src/DevCycleProvider.tsx
Labels: 1 min review

#558 fix: DVC-8888 update @openfeature/js-sdk dependency
  package.json
  yarn.lock
Labels: 1 min review

#559 ci: Implement a basic release workflow (DVC-8825)
  .github/workflows/release.yml
  README.md
  scripts/lerna-version-ci.sh
  scripts/npm-safe-publish.sh
Labels: 20 min review
