Repository DevCycleHQ/js-sdks, pull requests merged in 2023-11, with the labels that each got.

#587 chore(deps): update nx to 16.6.0
  .yarn/patches/@nx-js-npm-16.3.2-a543eca792.patch
  examples/react/react-native-app/metro.config.js
  examples/react/react-native-app/package.json
  examples/react/react-native-app/project.json
  lib/shared/bucketing-assembly-script/project.json
  lib/shared/bucketing/project.json
  lib/shared/config-manager/project.json
  lib/shared/server-request/project.json
  lib/shared/types/package.json
  lib/shared/types/project.json
  lib/shared/types/tsconfig.json
  migrations.json
  package.json
  sdk/js-cloud-server/tsconfig.lib.json
  sdk/js-cloud-server/tsconfig.spec.json
  sdk/nodejs/project.json
  sdk/react-native-expo/project.json
  sdk/react-native/project.json
  tsconfig.base.json
  yarn.lock
Labels: 10 min review

#589 fix: add react-client-sdk as a dependency to react-native-expo-client-sdk
  sdk/react-native-expo/package.json
  yarn.lock
Labels: 1 min review

#588 chore(deps): update nx to 16.7.4
  examples/js-cloud-server/cloudflare-worker/tsconfig.app.json
  examples/js/web-elements-app/tsconfig.app.json
  examples/js/web-elements-app/tsconfig.spec.json
  examples/nodejs-cloud/js/tsconfig.app.json
  examples/nodejs-cloud/js/tsconfig.spec.json
  examples/nodejs-cloud/typescript/tsconfig.app.json
  examples/nodejs-cloud/typescript/tsconfig.spec.json
  examples/nodejs-local/js/tsconfig.app.json
  examples/nodejs-local/js/tsconfig.spec.json
  examples/nodejs-local/typescript/tsconfig.app.json
  examples/nodejs-local/typescript/tsconfig.spec.json
  examples/openfeature-nodejs/project.json
  examples/openfeature-nodejs/tsconfig.app.json
  examples/openfeature-nodejs/tsconfig.spec.json
  examples/react/with-provider/tsconfig.app.json
  lib/shared/bucketing/tsconfig.json
  lib/shared/bucketing/tsconfig.spec.json
  lib/shared/config-manager/package.json
  lib/shared/config-manager/project.json
  lib/shared/config-manager/src/index.ts
  lib/shared/config-manager/tsconfig.spec.json
  lib/shared/server-request/package.json
  lib/shared/server-request/project.json
  migrations.json
  package.json
  sdk/js-cloud-server/package.json
  sdk/js-cloud-server/project.json
  sdk/js-cloud-server/tsconfig.lib.json
  sdk/js/package.json
  sdk/js/project.json
  sdk/nodejs/package.json
  sdk/nodejs/project.json
  sdk/nodejs/tsconfig.lib.json
  sdk/openfeature-nodejs-provider/package.json
  sdk/openfeature-nodejs-provider/project.json
  sdk/openfeature-nodejs-provider/tsconfig.lib.json
  sdk/openfeature-nodejs-provider/tsconfig.spec.json
  sdk/react-native-expo/.babelrc
  sdk/react-native/.babelrc
  sdk/react/package.json
  sdk/react/project.json
  sdk/react/tsconfig.lib.es5.json
  sdk/react/tsconfig.lib.json
  yarn.lock
Labels: 20 min review

#594 fix: circual dependancies between js-cloud-server and shared libs
  lib/shared/config-manager/__tests__/environmentConfigManager.spec.ts
  lib/shared/config-manager/src/index.ts
  lib/shared/types/src/index.ts
  lib/shared/types/src/types/apis/sdk/serverSDKTypes.ts
  sdk/js-cloud-server/src/cloudClient.ts
  sdk/js-cloud-server/src/index.ts
  sdk/js-cloud-server/src/request.ts
  sdk/js-cloud-server/src/types.ts
  sdk/nodejs/src/bucketing.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/index.ts
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
Labels: 10 min review

#595 fix: publish of js cloud server
  sdk/js-cloud-server/project.json
Labels: 1 min review

#596 chore: add public access flag to publish
  scripts/npm-safe-publish.sh
Labels: 1 min review

#598 chore: access public on main packages
  scripts/npm-safe-publish.sh
Labels: 1 min review

#601 fix: deferred init
  sdk/react/src/DevCycleProvider.tsx
  sdk/react/src/useVariableValue.ts
Labels: 1 min review

#602 fix: add tests for init in deferred mode and with boostrap config
  sdk/js/__tests__/Client.spec.js
  sdk/js/src/Client.ts
  sdk/react/src/useIsDevCycleInitialized.test.tsx
Labels: 5 min review

#600 fix: Remove protoc installation in workflows
  .github/workflows/nx-affected-test.yml
  .github/workflows/run-test-harness.yml
Labels: 1 min review, safe-changes

#603 fix: add resolution to dns-packet as it did not get updated by NX
  package.json
  yarn.lock
Labels: 1 min review

#604 fix: add resolution for loader-utils to fix security warning
  yarn.lock
Labels: 1 min review

#605 fix: add resolution for http-cache-semantics to fix dependancy warning
  yarn.lock
Labels: 1 min review

#606 fix: add resolution for json5 security warning
  yarn.lock
Labels: 1 min review

#607 fix: add resolution for postcss to resolve dependabot alert
  yarn.lock
Labels: 1 min review

#609 fix: add resolution for semver to resolve dependabot
  README.md
  package.json
  yarn.lock
Labels: 1 min review

#610 fix: update undici dependancy
  yarn.lock
Labels: 1 min review

#611 fix: update zod dependancy
  yarn.lock
Labels: 1 min review

#612 fix: update fast-xml-parser dependancy
  yarn.lock
Labels: 1 min review

#613 fix: update @babel/traverse dependancy
  yarn.lock
Labels: 1 min review

#618 chore: update axios dependancy
  package.json
  yarn.lock
Labels: 1 min review

#597 chore: remove deprecation system
  scripts/npm-safe-publish.sh
  sdk/js/project.json
  sdk/react-native/project.json
  sdk/react/project.json
Labels: 1 min review

#626 fix: openfeature examples, add README's for nextJS examples
  examples/nextjs/app-router/README.md
  examples/nextjs/pages-router/README.md
  examples/openfeature-nodejs/project.json
  examples/openfeature-web/src/app/app.element.ts
Labels: 1 min review

#627 fix: update openfeature-web dependancies
  package.json
  sdk/openfeature-web-provider/package.json
  yarn.lock
Labels: 1 min review

#628 chore: update openfeature node provider to latest version, add get status()
  package.json
  sdk/js-cloud-server/src/cloudClient.ts
  sdk/nodejs/src/client.ts
  sdk/openfeature-nodejs-provider/package.json
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
  yarn.lock
Labels: 1 min review

#629 chore: Change github assume role to OIDC
  .github/workflows/release.yml
Labels: 1 min review
