Repository DevCycleHQ/js-sdks, pull requests merged in 2023-06, with the labels that each got.

#492 [feat] add support for using devcycle in esm runtime
  lib/shared/bucketing-assembly-script/index.js
Labels: 1 min review

#493 chore: add note about privileges needed for releasing
  README.md
Labels: 1 min review, safe-changes

#498 chore: update yarn version
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.6.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: 1 min review

#503 fix: dont open streaming connection when EventSource is not available
  sdk/js/src/StreamingConnection.ts
Labels: 1 min review

#504 chore: DVC-7713 update test harness actions to run OpenFeature test harness
  .github/workflows/run-test-harness.yml
  yarn.lock
Labels: 1 min review, safe-changes

#505 chore: add semantic PR title enforcement
  .github/workflows/semantic-prs.yml
  .husky/commit-msg
  .husky/prepare-commit-msg
  package.json
  yarn.lock
Labels: 1 min review

#501 fix: DVC-7694 update OpenFeature provider to support 1.3.0
  .github/workflows/run-test-harness.yml
  package.json
  sdk/openfeature-nodejs-provider/__tests__/DevCycleProvider.test.ts
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
  yarn.lock
Labels: 5 min review

#508 feat(shared-bucketing-as): add echoString and echoUint8Array to bucketing-assembly-script
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
Labels: 1 min review

#509 fix: only return errorString when its defined
  .github/workflows/run-test-harness.yml
  examples/js/web-elements-app/src/main.ts
  sdk/js/src/Request.ts
Labels: 1 min review

#510 chore: update yarn 3.6
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.6.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: 1 min review

#511 chore: update learna version to get correct file path
  scripts/lerna-version.sh
Labels: 1 min review

#514 chore: patch nx js package to avoid adding devDependencies
  .gitignore
  .yarn/patches/@nx-js-npm-16.3.2-a543eca792.patch
  package.json
  yarn.lock
Labels: 1 min review

#513 fix: type generic arg on js client
  lib/shared/types/src/types/config/models/variable.ts
  sdk/js/src/index.test.ts
  sdk/js/src/index.ts
  sdk/js/src/types.ts
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
Labels: 5 min review

#515 fix: publish script for bucketing assemblyscript
  scripts/npm-safe-publish.sh
Labels: 1 min review

#517 fix: add variableValue method to exported types
  sdk/js/src/types.ts
Labels: 1 min review
