Repository DevCycleHQ/js-sdks, pull requests merged in 2023-12, with the labels that each got.

#631 feat: add support for pages router
  examples/nextjs/pages-router/pages/_app.tsx
  examples/nextjs/pages-router/pages/index.tsx
  sdk/nextjs/README.md
  sdk/nextjs/package.json
  sdk/nextjs/src/pages.ts
  sdk/nextjs/src/pages/appWithDevCycle.tsx
  sdk/nextjs/src/pages/bucketing.ts
  sdk/nextjs/src/pages/getServerSideDevCycle.ts
  sdk/nextjs/src/pages/types.ts
  sdk/nextjs/src/server/devcycleServerData.tsx
  tsconfig.base.json
  yarn.lock
Labels: 5 min review

#635 chore: prepare beta release for nextjs
  examples/nextjs/app-router/app/ClientIdentity.tsx
  examples/nextjs/app-router/app/ServerIdentity.tsx
  examples/nextjs/app-router/app/layout.tsx
  examples/nextjs/pages-router/pages/_app.tsx
  examples/nextjs/pages-router/pages/index.tsx
  sdk/nextjs/package.json
  tsconfig.base.json
  yarn.lock
Labels: 1 min review

#636 chore: re-export all react methods from next sdk
  sdk/nextjs/README.md
  sdk/nextjs/package.json
  sdk/nextjs/src/pages.ts
  sdk/react/src/index.ts
Labels: 1 min review

#637 chore: update @adobe/css-tools to resolve dependabot alert
  yarn.lock
Labels: 1 min review

#640 fix: package json exports structure
  sdk/nextjs/package.json
Labels: 1 min review

#642 fix: separate es5 build outputs and patch bundlefy to use the correct target
  .yarn/patches/@altack-nx-bundlefy-npm-0.16.0-fc464002e3.patch
  lib/shared/types/project.json
  package.json
  sdk/js/project.json
  sdk/react-native-expo/project.json
  sdk/react/project.json
  yarn.lock
Labels: 5 min review

#644 chore: add ignore-changes flag
  scripts/lerna-version-ci.sh
Labels: 1 min review

#645 chore: fix release by allowing nextjs tags
  scripts/lerna-version-ci.sh
  sdk/nextjs/package.json
Labels: 1 min review

#646 fix: an issue with != comparator for number filters with multiple filter values
  lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing/__tests__/segmentation.test.ts
  lib/shared/bucketing/src/segmentation.ts
Labels: 5 min review

#649 fix: streaming mode and readme
  sdk/nextjs/README.md
  sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
  sdk/nextjs/src/server/DevCycleServersideProvider.tsx
  sdk/nextjs/src/server/getVariableValue.ts
Labels: 1 min review

#647 chore: Nextjs e2e
  .eslintignore
  .github/workflows/nx-affected-e2e.yml
  e2e/nextjs/app-router/.eslintrc.json
  e2e/nextjs/app-router/app/.gitignore
  e2e/nextjs/app-router/app/.yarn/releases/yarn-4.0.2.cjs
  e2e/nextjs/app-router/app/.yarnrc.yml
  e2e/nextjs/app-router/app/app/ClientComponent.tsx
  e2e/nextjs/app-router/app/app/ServerComponent.tsx
  e2e/nextjs/app-router/app/app/layout.tsx
  e2e/nextjs/app-router/app/app/page.tsx
  e2e/nextjs/app-router/app/next.config.js
  e2e/nextjs/app-router/app/package.json
  e2e/nextjs/app-router/app/start.sh
  e2e/nextjs/app-router/app/tsconfig.json
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/app-router/playwright.config.ts
  e2e/nextjs/app-router/project.json
  e2e/nextjs/app-router/tests/app-router.spec.ts
  e2e/nextjs/pages-router/.eslintrc.json
  e2e/nextjs/pages-router/app/.gitignore
  e2e/nextjs/pages-router/app/.yarn/releases/yarn-4.0.2.cjs
  e2e/nextjs/pages-router/app/.yarnrc.yml
  e2e/nextjs/pages-router/app/next.config.js
  e2e/nextjs/pages-router/app/package.json
  e2e/nextjs/pages-router/app/pages/_app.tsx
  e2e/nextjs/pages-router/app/pages/_document.tsx
  e2e/nextjs/pages-router/app/pages/index.tsx
  e2e/nextjs/pages-router/app/start.sh
  e2e/nextjs/pages-router/app/tsconfig.json
  e2e/nextjs/pages-router/app/yarn.lock
  e2e/nextjs/pages-router/playwright.config.ts
  e2e/nextjs/pages-router/project.json
  e2e/nextjs/pages-router/tests/pages-router.spec.ts
  examples/nextjs/app-router/app/ClientIdentity.tsx
  examples/nextjs/app-router/app/ServerIdentity.tsx
  examples/nextjs/app-router/app/layout.tsx
  package.json
  sdk/nextjs/src/pages.ts
  sdk/nextjs/src/pages/bucketing.ts
  sdk/nextjs/src/pages/getServerSideDevCycle.ts
  sdk/nextjs/src/pages/types.ts
  sdk/nextjs/src/server/ably.ts
  sdk/nodejs/.eslintrc.json
  sdk/react/project.json
  tsconfig.base.json
  yarn.lock
Labels: 10 min review

#650 chore: fix nextjs readme
  sdk/nextjs/README.md
  sdk/nextjs/project.json
Labels: 1 min review

#648 feat: update to node 20
  .github/workflows/cf-worker-example-test.yml
  .github/workflows/nx-affected-test.yml
  .github/workflows/release.yml
  .github/workflows/run-test-harness.yml
  .nvmrc
  README.md
Labels: 1 min review

#651 fix: async local storage
  e2e/nextjs/app-router/app/yarn.lock
  sdk/nextjs/README.md
  sdk/nextjs/src/common/invalidateConfig.ts
  sdk/nextjs/src/server/DevCycleServersideProvider.tsx
  sdk/nextjs/src/server/bucketing.ts
  sdk/nextjs/src/server/initialize.ts
  sdk/nextjs/src/server/requestContext.ts
  sdk/nextjs/src/server/requests.ts
  sdk/nextjs/src/server/userAgent.ts
Labels: 5 min review

#652 feat: remove streaming mode with docs updates
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/app-router/playwright.config.ts
  e2e/nextjs/pages-router/app/yarn.lock
  examples/nextjs/app-router/app/layout.tsx
  package.json
  sdk/nextjs/README.md
  sdk/nextjs/package.json
  sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
  sdk/nextjs/src/client/useVariableValue.ts
  sdk/nextjs/src/server/DevCycleServersideProvider.tsx
  sdk/nextjs/src/server/initialize.ts
  yarn.lock
Labels: 5 min review

#654 fix: issues found in nextjs docs
  sdk/nextjs/README.md
Labels: 1 min review, safe-changes

#655 fix: re-add react cache
  e2e/nextjs/app-router/app/app/layout.tsx
  e2e/nextjs/app-router/app/package.json
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/pages-router/app/package.json
  e2e/nextjs/pages-router/app/yarn.lock
  sdk/nextjs/src/server/DevCycleServersideProvider.tsx
  sdk/nextjs/src/server/requestContext.ts
  sdk/nextjs/src/server/userAgent.ts
Labels: 5 min review

#656 feat: bring back streaming mode with docs updates
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/app-router/playwright.config.ts
  e2e/nextjs/pages-router/app/yarn.lock
  examples/nextjs/app-router/app/layout.tsx
  package.json
  sdk/nextjs/README.md
  sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
  sdk/nextjs/src/client/useVariableValue.ts
  sdk/nextjs/src/server/DevCycleServersideProvider.tsx
  sdk/nextjs/src/server/initialize.ts
  yarn.lock
Labels: 5 min review

#657 fix: promise init
  sdk/nextjs/src/server/getVariableValue.ts
Labels: 1 min review

#658 fix: deferred mode check and add tests
  sdk/js/__tests__/Client.spec.js
  sdk/js/__tests__/index.test.ts
  sdk/js/src/Client.ts
  sdk/js/src/index.ts
  sdk/openfeature-web-provider/__mocks__/@devcycle/js-client-sdk.ts
Labels: 5 min review
