Repository DevCycleHQ/js-sdks, pull requests merged in 2023-05, with the labels that each got.

#483 DVC-7110 OpenFeature NodeJS Provider
  examples/nodejs-local/typescript/src/main.ts
  examples/openfeature-nodejs/.eslintrc.json
  examples/openfeature-nodejs/README.md
  examples/openfeature-nodejs/package.json
  examples/openfeature-nodejs/project.json
  examples/openfeature-nodejs/src/main.ts
  examples/openfeature-nodejs/tsconfig.app.json
  examples/openfeature-nodejs/tsconfig.json
  examples/openfeature-nodejs/tsconfig.spec.json
  lib/shared/types/jest.config.ts
  lib/shared/types/src/utils.ts
  package.json
  sdk/nodejs/src/index.ts
  sdk/openfeature-nodejs-provider/.babelrc
  sdk/openfeature-nodejs-provider/.eslintrc.json
  sdk/openfeature-nodejs-provider/README.md
  sdk/openfeature-nodejs-provider/__tests__/DevCycleProvider.test.ts
  sdk/openfeature-nodejs-provider/jest.config.ts
  sdk/openfeature-nodejs-provider/package.json
  sdk/openfeature-nodejs-provider/project.json
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
  sdk/openfeature-nodejs-provider/src/index.ts
  sdk/openfeature-nodejs-provider/tsconfig.json
  sdk/openfeature-nodejs-provider/tsconfig.lib.json
  sdk/openfeature-nodejs-provider/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: 20 min review

#486 add variableValue() method to NodeJS Local / Cloud + JS SDK
  .eslintrc.json
  examples/js/web-elements-app/src/app/app.element.ts
  examples/nodejs-cloud/js/src/main.js
  examples/nodejs-cloud/typescript/src/main.ts
  examples/nodejs-local/js/src/main.js
  examples/nodejs-local/typescript/src/main.ts
  lib/shared/types/src/types/config/models/variable.ts
  sdk/js/__tests__/Client.spec.js
  sdk/js/src/Client.ts
  sdk/js/src/types.ts
  sdk/nodejs/__tests__/client.spec.ts
  sdk/nodejs/__tests__/cloudClient.spec.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/cloudClient.ts
Labels: 5 min review

#490 fix: enable inline sources to avoid parsing errors
  tsconfig.base.json
Labels: 1 min review
