Repository DevCycleHQ/js-sdks, pull requests merged in 2024-04, with the labels that each got.

#788 feat: Add DevCycleService to Nest SDK
  sdk/nestjs/src/DevCycleModule/DevCycleModule.ts
  sdk/nestjs/src/DevCycleModule/DevCycleService.ts
  sdk/nestjs/src/DevCycleModule/RequestWithData.ts
  sdk/nestjs/src/DevCycleModule/index.ts
  sdk/nestjs/src/RequireVariableValue.ts
  sdk/nestjs/src/VariableValue.ts
  sdk/nestjs/src/__mocks__/DevCycleModule.ts
Labels: 5 min review

#792 fix: Update nest sdk to use nest-cls
  sdk/nestjs/.eslintrc.json
  sdk/nestjs/package.json
  sdk/nestjs/src/DevCycleModule/DevCycleModule.ts
  sdk/nestjs/src/DevCycleModule/DevCycleService.ts
  sdk/nestjs/src/DevCycleModule/RequestInterceptor.test.ts
  sdk/nestjs/src/DevCycleModule/RequestInterceptor.ts
  sdk/nestjs/src/DevCycleModule/RequestWithData.ts
  sdk/nestjs/src/RequireVariableValue.ts
  sdk/nestjs/src/VariableValue.test.ts
  sdk/nestjs/src/VariableValue.ts
  yarn.lock
Labels: 5 min review

#796 fix: Add missing ClsModule to Nest SDK mocks
  sdk/nestjs/src/__mocks__/DevCycleModule.ts
Labels: 1 min review

#741 feat: SSE Config Property Schema
  lib/shared/types/src/types/config/configBody.ts
Labels: 1 min review

#805 fix: overwriting global.fetch in tests with cross-fetch
  sdk/js-cloud-server/__tests__/cloudClient.spec.ts
Labels: 1 min review, safe-changes

#806 fix: Remove channel from the type.
  lib/shared/types/src/types/config/configBody.ts
Labels: 1 min review

#802 chore: remove audience _id field from config and update bucketing code
  lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
  lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-assembly-script/assembly/types/target.ts
  lib/shared/bucketing-test-data/src/data/largeConfig.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/bucketing/src/bucketing.ts
  lib/shared/types/src/types/config/models/audience.ts
  lib/shared/types/src/types/config/models/featureConfiguration.ts
Labels: 5 min review

#814 chore: dependabot security updates
  yarn.lock
Labels: 1 min review

#810 chore: ignore nx in dependabot
  .github/dependabot.yml
Labels: 1 min review

#820 chore: move js sdk to peer dependencies for debugger
  lib/web-debugger/package.json
  yarn.lock
Labels: 1 min review

#822 fix: react import path in debugger
  lib/web-debugger/index.ts
  lib/web-debugger/package.json
  lib/web-debugger/project.json
  lib/web-debugger/react.tsx
  lib/web-debugger/src/index.ts
  lib/web-debugger/tsconfig.lib.json
  lib/web-debugger/tsconfig.spec.json
  sdk/nextjs/project.json
  sdk/nextjs/tsconfig.spec.json
Labels: 5 min review

#823 chore: fix publish path for debugger
  lib/web-debugger/project.json
Labels: 1 min review

#824 fix: update imports to use js extensions for es modules
  lib/web-debugger/index.ts
  lib/web-debugger/package.json
  lib/web-debugger/react.tsx
Labels: 1 min review

#825 chore: Change dependabot to weekly
  .github/dependabot.yml
Labels: 1 min review

#826 fix: update debugger flag evaluation
  lib/web-debugger/src/initializeDevCycleDebugger.test.ts
  lib/web-debugger/src/initializeDevCycleDebugger.ts
Labels: 5 min review

#827 chore: Fix example apps resolution
  examples/react/project.json
  examples/react/tsconfig.json
  examples/react/webpack.config.js
  lib/web-debugger/package.json
  tsconfig.base.json
Labels: 5 min review

#740 feat: Add support for service workers by using indexedDB instead of localStorage
  sdk/js/__tests__/Client.spec.js
  sdk/js/__tests__/EventEmitter.spec.js
  sdk/js/__tests__/EventQueue.spec.js
  sdk/js/src/CacheStore.ts
  sdk/js/src/Client.ts
  sdk/js/src/ConfigRequestConsolidator.ts
  sdk/js/src/DefaultCacheStore.ts
  sdk/js/src/DefaultStorage.ts
  sdk/js/src/index.ts
  sdk/js/src/types.ts
  sdk/js/src/utils.ts
  sdk/js/tsconfig.lib.es5.json
  sdk/js/tsconfig.lib.json
  sdk/openfeature-web-provider/__tests__/DevCycleProvider.test.ts
  sdk/react-native-expo/src/ReactNativeCacheStore.ts
  sdk/react-native/src/ReactNativeCacheStore.ts
Labels: 10 min review

#830 add a statement about how the sdk relies on fetch with a link to how …
  sdk/js/README.md
  sdk/nextjs/README.md
  sdk/react/README.md
Labels: 1 min review, safe-changes

#831 fix capitalization of api
  sdk/nextjs/README.md
  sdk/react/README.md
Labels: 1 min review
