Repository DevCycleHQ/js-sdks, pull requests merged in 2024-05, with the labels that each got.

#832 feat: add disablePassthroughRollouts to project settings
  lib/shared/types/src/types/config/models/project.ts
Labels: 1 min review

#828 feat: use last-modified header to send If-Modified-Since header in config CDN request
  examples/nodejs-cloud/README.md
  examples/nodejs-local/README.md
  lib/shared/config-manager/__tests__/request.spec.ts
  lib/shared/config-manager/src/index.ts
  lib/shared/config-manager/src/request.ts
Labels: 1 min review

#749 feat: nodejs bootstrapping mode
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/config-manager/src/index.ts
  lib/shared/types/src/types/apis/sdk/serverSDKTypes.ts
  lib/shared/types/src/types/config/configBody.ts
  sdk/js-cloud-server/src/models/populatedUser.ts
  sdk/nodejs/.eslintrc.json
  sdk/nodejs/project.json
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/clientUser.ts
  sdk/nodejs/src/utils/userBucketingHelper.ts
Labels: 10 min review

#836 fix: rename sdkKey field
  lib/shared/bucketing-assembly-script/assembly/index.ts
  lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
  lib/shared/bucketing-test-data/src/data/testData.ts
  lib/shared/types/src/types/config/configBody.ts
  sdk/nodejs/src/client.ts
Labels: 1 min review

#837 chore: fix module resolution settings
  sdk/js/tsconfig.lib.json
  sdk/react-native-expo/tsconfig.json
  sdk/react-native/tsconfig.json
Labels: 1 min review

#839 fix: remove warning about window being undefined
  sdk/js/src/index.ts
Labels: 1 min review

#838 feat: add SSEConnection shared lib
  lib/shared/sse-connection/.eslintrc.json
  lib/shared/sse-connection/README.md
  lib/shared/sse-connection/jest.config.ts
  lib/shared/sse-connection/project.json
  lib/shared/sse-connection/src/index.ts
  lib/shared/sse-connection/src/lib/SSEConnection.spec.ts
  lib/shared/sse-connection/src/lib/SSEConnection.ts
  lib/shared/sse-connection/tsconfig.json
  lib/shared/sse-connection/tsconfig.lib.json
  lib/shared/sse-connection/tsconfig.spec.json
  tsconfig.base.json
Labels: 5 min review
