Repository DevCycleHQ/js-sdks, pull requests merged in 2024-01, with the labels that each got.

#659 fix: call close on correct reference to client
  sdk/react/src/DevCycleProvider.tsx
  sdk/react/src/useIsDevCycleInitialized.test.tsx
Labels: 1 min review

#660 chore: update readme requirements
  sdk/nextjs/README.md
Labels: 1 min review, safe-changes

#662 fix: add user agent to clientside
  sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
  sdk/nextjs/src/server/setupDevCycle.ts
Labels: 1 min review

#664 feat: add missing methods for SDK
  e2e/nextjs/app-router/app/.eslintrc.json
  sdk/nextjs/README.md
  sdk/nextjs/src/client/internal/context.ts
  sdk/nextjs/src/client/internal/useDevCycleClient.ts
  sdk/nextjs/src/client/internal/useRerenderOnVariableChange.ts
  sdk/nextjs/src/client/updateDVCCookie.ts
  sdk/nextjs/src/client/useAllFeatures.ts
  sdk/nextjs/src/client/useAllVariables.ts
  sdk/nextjs/src/client/useTrack.ts
  sdk/nextjs/src/client/useUserIdentity.ts
  sdk/nextjs/src/client/useVariableValue.ts
  sdk/nextjs/src/index.ts
Labels: 5 min review

#665 fix: streaming in cases where the promise resolves before the layout is rendered
  e2e/nextjs/app-router/app/app/layout.tsx
  e2e/nextjs/app-router/app/app/page.tsx
  e2e/nextjs/app-router/app/app/shared.ts
  e2e/nextjs/app-router/app/package.json
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/pages-router/app/package.json
  e2e/nextjs/pages-router/app/yarn.lock
  sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
  sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
  sdk/nextjs/src/common/types.ts
  sdk/nextjs/src/server/getVariableValue.ts
  sdk/nextjs/src/server/initialize.ts
  sdk/nextjs/src/server/setupDevCycle.ts
Labels: 10 min review

#670 chore: replace @openfeature/js-sdk with @openfeature/server-sdk
  examples/openfeature-nodejs/src/main.ts
  package.json
  sdk/openfeature-nodejs-provider/README.md
  sdk/openfeature-nodejs-provider/__tests__/DevCycleProvider.test.ts
  sdk/openfeature-nodejs-provider/package.json
  sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
  yarn.lock
Labels: 1 min review

#671 chore: update E2E tests to use Node 20
  .github/workflows/nx-affected-e2e.yml
Labels: 1 min review

#674 chore: esm hybrid publish
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/pages-router/app/yarn.lock
  lib/shared/types/project.json
  lib/shared/types/src/utils.ts
  sdk/js/package.json
  sdk/js/project.json
  sdk/js/src/CacheStore.ts
  sdk/js/src/Client.ts
  sdk/js/src/ConfigRequestConsolidator.ts
  sdk/js/src/Request.ts
  sdk/js/src/StreamingConnection.ts
  sdk/js/src/Variable.ts
  sdk/js/src/logger.ts
  sdk/js/src/types.ts
  sdk/js/src/utils.ts
  sdk/js/tsconfig.lib.json
  sdk/react/src/useVariableValue.ts
Labels: 5 min review

#678 fix: NextJS example apps to use new SDK interface
  examples/nextjs/app-router/app/ServerIdentity.tsx
  examples/nextjs/app-router/app/devcycle.tsx
  examples/nextjs/app-router/app/layout.tsx
  sdk/nextjs/README.md
Labels: 1 min review

#680 fix: return defaults on config fetch error instead of throwing
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/pages-router/app/yarn.lock
  sdk/js/src/Client.ts
  sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
  sdk/nextjs/src/pages/appWithDevCycle.tsx
  sdk/nextjs/src/pages/getServerSideDevCycle.ts
  sdk/nextjs/src/pages/types.ts
  sdk/nextjs/src/server/bucketing.ts
  sdk/nextjs/src/server/devcycleServerData.tsx
Labels: 5 min review

#677 chore: use rollup for es5 build for js
  lib/shared/types/project.json
  sdk/js/project.json
  sdk/js/tsconfig.lib.es5.json
  sdk/openfeature-nodejs-provider/package.json
  sdk/react/project.json
  yarn.lock
Labels: 5 min review

#682 chore: update wrangler for dependabot
  package.json
  yarn.lock
Labels: 1 min review

#672 chore: update readme and strip irrelevant options from type
  sdk/nextjs/README.md
  sdk/nextjs/package.json
  sdk/nextjs/src/server/initialize.ts
  yarn.lock
Labels: 1 min review

#683 chore: update track method and readme
  sdk/nextjs/README.md
  sdk/nextjs/src/client/useAllFeatures.ts
  sdk/nextjs/src/client/useAllVariables.ts
  sdk/nextjs/src/client/useTrack.ts
  sdk/nextjs/src/pages/appWithDevCycle.tsx
  sdk/nextjs/src/server/allFeatures.ts
  sdk/nextjs/src/server/getAllVariables.ts
  sdk/nextjs/src/server/getVariableValue.ts
  sdk/nextjs/src/server/initialize.ts
  sdk/nextjs/src/server/setupDevCycle.ts
Labels: 5 min review

#684 fix: docs and provide options to client
  sdk/nextjs/README.md
  sdk/nextjs/package.json
  sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
  sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
  sdk/nextjs/src/common/types.ts
  sdk/nextjs/src/server/initialize.ts
  sdk/nextjs/src/server/requestContext.ts
  sdk/nextjs/src/server/setupDevCycle.ts
  yarn.lock
Labels: 5 min review

#685 fix: realtime updates with streaming off
  e2e/nextjs/app-router/app/yarn.lock
  sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
  sdk/nextjs/src/common/invalidateConfig.ts
Labels: 1 min review

#689 fix: change peer dep
  e2e/nextjs/app-router/app/yarn.lock
  sdk/nextjs/package.json
  yarn.lock
Labels: 1 min review

#691 fix: move promise await to fix static builds
  sdk/nextjs/src/server/allFeatures.ts
  sdk/nextjs/src/server/getAllVariables.ts
  sdk/nextjs/src/server/getVariableValue.ts
  sdk/nextjs/src/server/setupDevCycle.ts
Labels: 1 min review

#692 fix: eliminate a bunch of the shared context stuff and move the user agent call
  e2e/nextjs/app-router/app/app/normal/devcycle.ts
  e2e/nextjs/app-router/app/app/streaming/devcycle.ts
  e2e/nextjs/app-router/app/next.config.js
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/app-router/playwright.config.ts
  e2e/nextjs/app-router/tests/app-router.spec.ts
  e2e/nextjs/pages-router/app/yarn.lock
  sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
  sdk/nextjs/src/common/types.ts
  sdk/nextjs/src/server.ts
  sdk/nextjs/src/server/bucketing.ts
  sdk/nextjs/src/server/devcycleServerData.tsx
  sdk/nextjs/src/server/identify.ts
  sdk/nextjs/src/server/initialize.ts
  sdk/nextjs/src/server/requestContext.ts
  sdk/nextjs/src/server/setupDevCycle.ts
  sdk/nextjs/src/server/userAgent.ts
Labels: 10 min review

#695 fix: move entry files to root
  sdk/nextjs/index.ts
  sdk/nextjs/package.json
  sdk/nextjs/pages.ts
  sdk/nextjs/project.json
  sdk/nextjs/server.ts
  sdk/nextjs/src/index.ts
  sdk/nextjs/src/server.ts
  sdk/nextjs/tsconfig.lib.json
Labels: 1 min review

#697 chore: release next 1.0
  sdk/nextjs/package.json
Labels: 1 min review

#704 feat: add IfEnabled helper
  e2e/nextjs/app-router/app/app/normal/ClientComponent.tsx
  e2e/nextjs/app-router/app/app/normal/ConditionalClientComponent.tsx
  e2e/nextjs/app-router/app/app/normal/devcycle.ts
  e2e/nextjs/app-router/app/app/normal/page.tsx
  e2e/nextjs/app-router/app/package.json
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/app-router/tests/app-router.spec.ts
  sdk/nextjs/index.ts
  sdk/nextjs/src/client/renderIfEnabled.tsx
  sdk/nextjs/src/server/setupDevCycle.tsx
Labels: 5 min review

#706 chore: combine dependabot updates into one PR
  package.json
  yarn.lock
Labels: 1 min review

#707 feat: move NodeJS OpenFeature Provider into NodeJS SDK, using `getOpenFeatureProvider()` method
  examples/openfeature-nodejs/src/main.ts
  package.json
  sdk/nodejs/.eslintrc.json
  sdk/nodejs/__tests__/initialize.spec.ts
  sdk/nodejs/__tests__/open-feature-provider/DevCycleProvider.test.ts
  sdk/nodejs/package.json
  sdk/nodejs/src/__mocks__/bucketing.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/index.ts
  sdk/nodejs/src/open-feature-provider/DevCycleProvider.ts
  sdk/openfeature-nodejs-provider/.babelrc
  sdk/openfeature-nodejs-provider/.eslintrc.json
  sdk/openfeature-nodejs-provider/README.md
  sdk/openfeature-nodejs-provider/jest.config.ts
  sdk/openfeature-nodejs-provider/package.json
  sdk/openfeature-nodejs-provider/project.json
  sdk/openfeature-nodejs-provider/src/index.ts
  sdk/openfeature-nodejs-provider/tsconfig.json
  sdk/openfeature-nodejs-provider/tsconfig.lib.json
  sdk/openfeature-nodejs-provider/tsconfig.spec.json
  yarn.lock
Labels: 5 min review

#713 chore: cleanup openfeature-nodejs-provider refrences
  .github/workflows/run-test-harness.yml
  tsconfig.base.json
Labels: 1 min review

#716 feat: update NodeJS SDK to enable getOpenFeatureProvider() for cloud bucketing
  sdk/js-cloud-server/src/cloudClient.ts
  sdk/nodejs/__tests__/initialize.spec.ts
  sdk/nodejs/__tests__/open-feature-provider/DevCycleProvider.test.ts
  sdk/nodejs/src/client.ts
  sdk/nodejs/src/index.ts
  sdk/nodejs/src/open-feature-provider/DevCycleProvider.ts
Labels: 5 min review

#717 feat: update OpenFeature web provider to emit configUpdated and error events
  sdk/openfeature-web-provider/package.json
  sdk/openfeature-web-provider/src/DevCycleProvider.ts
  yarn.lock
Labels: 1 min review

#718 add next to release process
  scripts/lerna-version-ci.sh
Labels: 1 min review

#712 chore: more dependabot updates
  package.json
  yarn.lock
Labels: 1 min review

#722 fix: OpenFeature Web Provider exporting events emitter
  sdk/openfeature-web-provider/src/DevCycleProvider.ts
Labels: 1 min review

#724 fix: react strictmode closing wrong client again
  sdk/react/src/DevCycleProvider.tsx
Labels: 1 min review

#723 chore: change OpenFeature dependancies to peerDependencies
  package.json
  sdk/nodejs/package.json
  sdk/openfeature-web-provider/package.json
  sdk/openfeature-web-provider/src/DevCycleProvider.ts
  yarn.lock
Labels: 1 min review
