Repository DevCycleHQ/js-sdks, pull requests merged in 2024-03, with the labels that each got.

#744 chore: add obfuscation fields to project settings config type
  lib/shared/types/src/types/config/models/project.ts
Labels: 1 min review

#745 fix: revert axios to fetch migration
  lib/shared/server-request/src/request.ts
  nx.json
  package.json
  sdk/js-cloud-server/package.json
  sdk/js/__mocks__/cross-fetch.ts
  sdk/js/__mocks__/fetch-retry.ts
  sdk/js/__tests__/Client.test.ts
  sdk/js/__tests__/Request.spec.ts
  sdk/js/jest.config.ts
  sdk/js/package.json
  sdk/js/src/Request.ts
  sdk/js/src/RequestUtils.ts
  sdk/js/tsconfig.lib.es5.json
  sdk/js/tsconfig.lib.json
  sdk/js/tsconfig.spec.json
  sdk/nodejs/package.json
  yarn.lock
Labels: 10 min review

#746 chore: disable release action
  .github/workflows/release.yml
Labels: 1 min review

#751 chore: add e2e test for minified cdn build of js sdk
  .github/workflows/nx-affected-e2e.yml
  .github/workflows/release.yml
  .gitignore
  e2e/js/js-cdn/.eslintrc.json
  e2e/js/js-cdn/README.md
  e2e/js/js-cdn/e2e/example.spec.ts
  e2e/js/js-cdn/playwright.config.ts
  e2e/js/js-cdn/project.json
  e2e/js/js-cdn/scripts/copy-sdk.js
  e2e/js/js-cdn/src/app/app.element.ts
  e2e/js/js-cdn/src/assets/.gitkeep
  e2e/js/js-cdn/src/environments/environment.prod.ts
  e2e/js/js-cdn/src/environments/environment.ts
  e2e/js/js-cdn/src/favicon.ico
  e2e/js/js-cdn/src/index.html
  e2e/js/js-cdn/src/main.ts
  e2e/js/js-cdn/src/styles.css
  e2e/js/js-cdn/tsconfig.app.json
  e2e/js/js-cdn/tsconfig.json
  e2e/js/js-cdn/tsconfig.spec.json
  e2e/js/js-cdn/webpack.config.js
  e2e/nextjs/pages-router/app/yarn.lock
  package.json
  sdk/js/project.json
  tsconfig.base.json
  yarn.lock
Labels: 10 min review

#754 chore: update GH Action Upload CDN Release task to upload to versioned paths
  .github/workflows/release.yml
  scripts/npm-safe-publish.sh
Labels: 1 min review

#748 feat: implement obfuscation in SDK
  package.json
  sdk/js/__tests__/Client.spec.js
  sdk/js/__tests__/EventQueue.spec.js
  sdk/js/__tests__/Request.spec.ts
  sdk/js/src/EventQueue.ts
  sdk/js/src/Request.ts
  sdk/js/src/types.ts
  sdk/nextjs/src/common/types.ts
  yarn.lock
Labels: 5 min review

#756 feat: add obfuscation support to nextjs
  e2e/nextjs/app-router/.eslintrc.json
  e2e/nextjs/app-router/app/app/obfuscated/ClientComponent.tsx
  e2e/nextjs/app-router/app/app/obfuscated/ConditionalClientComponent.tsx
  e2e/nextjs/app-router/app/app/obfuscated/ServerComponent.tsx
  e2e/nextjs/app-router/app/app/obfuscated/devcycle.ts
  e2e/nextjs/app-router/app/app/obfuscated/layout.tsx
  e2e/nextjs/app-router/app/app/obfuscated/page.tsx
  e2e/nextjs/app-router/app/app/obfuscated/test/ClientComponent.tsx
  e2e/nextjs/app-router/app/app/obfuscated/test/ServerComponent.tsx
  e2e/nextjs/app-router/app/app/obfuscated/test/page.tsx
  e2e/nextjs/app-router/app/dvcVariableTypes.ts
  e2e/nextjs/app-router/app/yarn.lock
  e2e/nextjs/app-router/tests/app-router.spec.ts
  sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
  sdk/nextjs/src/common/invalidateConfig.ts
  sdk/nextjs/src/server/bucketing.ts
  sdk/nextjs/src/server/initialize.ts
  sdk/nextjs/src/server/requests.ts
  sdk/nextjs/src/server/setupDevCycle.tsx
Labels: 10 min review

#752 feat: Setup Nest.js SDK
  package.json
  sdk/nestjs/.babelrc
  sdk/nestjs/.eslintrc.json
  sdk/nestjs/.gitignore
  sdk/nestjs/.test.env
  sdk/nestjs/README.md
  sdk/nestjs/jest.config.ts
  sdk/nestjs/package.json
  sdk/nestjs/project.json
  sdk/nestjs/src/DevCycleModule/DevCycleModule.ts
  sdk/nestjs/src/DevCycleModule/DevCycleModuleOptions.ts
  sdk/nestjs/src/DevCycleModule/RequestInterceptor.test.ts
  sdk/nestjs/src/DevCycleModule/RequestInterceptor.ts
  sdk/nestjs/src/DevCycleModule/index.ts
  sdk/nestjs/src/RequireVariableValue.ts
  sdk/nestjs/src/VariableValue.test.ts
  sdk/nestjs/src/VariableValue.ts
  sdk/nestjs/src/index.ts
  sdk/nestjs/tsconfig.json
  sdk/nestjs/tsconfig.lib.json
  sdk/nestjs/tsconfig.spec.json
  yarn.lock
Labels: 10 min review

#768 fix: update the AbortError to indicate a network connection timeout
  sdk/js/src/RequestUtils.ts
Labels: 1 min review

#759 chore: add e2e tetss for js-cloud-server-sdk
  .github/workflows/nx-affected-e2e.yml
  e2e/js/js-cloud-server/.eslintrc.json
  e2e/js/js-cloud-server/.gitignore
  e2e/js/js-cloud-server/README.md
  e2e/js/js-cloud-server/jest.config.ts
  e2e/js/js-cloud-server/package.json
  e2e/js/js-cloud-server/project.json
  e2e/js/js-cloud-server/src/index.ts
  e2e/js/js-cloud-server/start.sh
  e2e/js/js-cloud-server/tests/js-cloud-server.spec.ts
  e2e/js/js-cloud-server/tsconfig.app.json
  e2e/js/js-cloud-server/tsconfig.json
  e2e/js/js-cloud-server/tsconfig.spec.json
  e2e/js/js-cloud-server/wrangler.toml
  e2e/js/js-cloud-server/yarn.lock
  package.json
  yarn.lock
Labels: 5 min review

#772 chore: re-enable js sdk release process
  .github/workflows/release.yml
Labels: 1 min review

#773 fix: the github workflow for uploading a versioned endpoint for the cd…
  .github/workflows/release.yml
Labels: 1 min review

#761 feat: add tracking for sdkPlatform query param
  sdk/js/__tests__/Client.spec.js
  sdk/js/__tests__/Request.spec.ts
  sdk/js/src/Client.ts
  sdk/js/src/Request.ts
  sdk/js/src/types.ts
  sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
  sdk/nextjs/src/pages/appWithDevCycle.tsx
  sdk/nextjs/src/server/initialize.ts
  sdk/openfeature-web-provider/src/DevCycleProvider.ts
  sdk/react-native-expo/src/DevCycleProvider.tsx
  sdk/react-native/src/DevCycleProvider.tsx
  sdk/react/src/initializeDevCycleClient.ts
Labels: 5 min review

#781 chore: remove nrwl jest package
  package.json
  yarn.lock
Labels: 1 min review

#786 feat: Add mocks to nestjs sdk
  sdk/nestjs/.eslintrc.json
  sdk/nestjs/mocks.ts
  sdk/nestjs/src/__mocks__/DevCycleClient.ts
  sdk/nestjs/src/__mocks__/DevCycleModule.ts
  sdk/nestjs/src/__mocks__/RequireVariableValue.ts
  sdk/nestjs/src/__mocks__/VariableValue.ts
  sdk/nestjs/src/__mocks__/index.ts
  sdk/nestjs/tsconfig.lib.json
Labels: 5 min review
